input {
  http {
    port => 8089
  }
}
filter {
  mutate {
    add_field => { "project" => "orbitdata" }
  }
}
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "orbitdata-logs"
  }
  stdout { codec => rubydebug }
}