global:
  resolve_timeout: 5m
  pagerduty_url: "https://events.pagerduty.com/generic/2010-04-15/create_event.json"

route:
  receiver: 'pagerduty_notifications'
receivers:
- name: "pagerduty_notifications"
  pagerduty_configs:
  - service_key: 2e25b5e491bf4407c0a462337b61a761
    send_resolved: true
inhibit_rules:
  - source_matchers: [severity="critical"]
    target_matchers: [severity="warning"]
    # Apply inhibition if the alertname is the same.
    # CAUTION:
    #   If all label names listed in `equal` are missing
    #   from both the source and target alerts,
    #   the inhibition rule will apply!
    equal: [alertname, dev, instance]
